### ISSUE TITLE
Doesn't work in brackets sprint 28

### ISSUE THREAD

**Issue by yoshuawuyts** [couzteau/brackets-git-info#1]
This extension is faulty in the lastest brackets sprint.

**Comment by yoshuawuyts** [comment]
Or maybe I haven't enabled it properly, but I wouldn't know how (no option in 'View' to toggle it on/off)

**Comment by couzteau** [comment]
I tried both Brackets Sprint 28 and 30 and found it working fine. Please try to install from Extension Manager / Available tab

**Comment by yoshuawuyts** [comment]
Yep, must agree on this one. I forgot that I had opened an issue. Thanks for checking this issue, I wish you luck on further developing this extension!
