### ISSUE TITLE
Recursive tests console error on window focus

### ISSUE THREAD

**Issue by lkcampbell** [couzteau/brackets-git-info#3]
OS: Windows 7

Brackets Build: sprint 31 experimental build 0.31.0-9569 (On branch sprint-31-hotfix,sprint-31-hotfix dd28c6a6e)

Extension Version: 1.0.3

Repro Steps:
1. Open a project.
2. Open Dev Tools and go to the console log.
3. Jump back and forth between the Dev Tools window and the Brackets window.

Observed Results:
Every time the Brackets window receives focus, the following console error pops up in the log:
`Recursive tests with the same name are not supported. Timer name: readAsText:  C:/Users/Lance/brackets/.git/HEAD PerfUtils.js:115`

Expected Results:
No console error message.

**Comment by lkcampbell** [comment]
I believe this issue may have something to do with it: https://github.com/adobe/brackets/issues/2346

**Comment by isonno** [comment]
Could this also be why the branch name doesn't seem to be updating in the menu on focus anymore (see #2 )?

**Comment by wormeyman** [comment]
I can confirm this as well.

**Comment by lkcampbell** [comment]
Closing, this extension is clearly not being maintained.
