### ISSUE TITLE
Breaking another brackets git plugin

### ISSUE THREAD

**Issue by talamaska** [couzteau/brackets-git-info#5]
your plugin is hiding the the branch name from git from another plugin - Brackets Git.
https://github.com/zaggino/brackets-git

I think the problem is with that 93% of width on #project-dropdown-toggle

![untitled](https://f.cloud.github.com/assets/299973/1344484/4700aa3a-3681-11e3-8283-2410c767e6d1.png)

**Comment by couzteau** [comment]
Thanks @talamaska. I  have removed the style in version 1.0.5. It was causing other problems too.  I hope this fixes your  issue.

**Comment by talamaska** [comment]
thanks, I'm gonna check

On 17 October 2013 06:31, Jochen notifications@github.com wrote:

> Thanks @talamaska https://github.com/talamaska. I have removed the
> style in version 1.0.5. It was causing other problems too. I hope this
> fixes your issue.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/couzteau/brackets-git-info/issues/5#issuecomment-26477037
> .

## 

Best Regards,
Zlati Pehlivanov

**Comment by talamaska** [comment]
yep this is issue is fixed

On 17 October 2013 12:58, Zlati Pehlivanov zlati.pehlivanov@gmail.comwrote:

> thanks, I'm gonna check
> 
> On 17 October 2013 06:31, Jochen notifications@github.com wrote:
> 
> > Thanks @talamaska https://github.com/talamaska. I have removed the
> > style in version 1.0.5. It was causing other problems too. I hope this
> > fixes your issue.
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/couzteau/brackets-git-info/issues/5#issuecomment-26477037
> > .
> 
> ## 
> 
> Best Regards,
> Zlati Pehlivanov

## 

Best Regards,
Zlati Pehlivanov
