### ISSUE TITLE
Branch doesn't update in folder menu

### ISSUE THREAD

**Issue by isonno** [couzteau/brackets-git-info#7]
Same as #2 (I can't re-open it), but it doesn't seem to be working; you have to re-launch brackets to see a branch change.  This on Sprint 36/Mac OSX.  Perhaps related to #6 or #3 ?

**Comment by couzteau** [comment]
This was broken when Brackets introduced the updated file watchers. The shell seems to cache the file and returns stale data for the file contents of `.git/HEAD`

**Comment by couzteau** [comment]
fixed in 1.0.7
