### ISSUE TITLE
Not working on sprint 41

### ISSUE THREAD

**Issue by felipekm** [couzteau/brackets-git-info#8]
Not showing it self for me on this version, anyone else?

**Comment by couzteau** [comment]
Taking a look. Thanks.

**Comment by couzteau** [comment]
Hmm, works for me. also .42 works fine. Anything on console log? Is another extensio failing to load maybe?

**Comment by felipekm** [comment]
I just installed the last one (0.42) and it's working fine. :smile:

**Comment by couzteau** [comment]
Thanks for the update. Closing.
